title: "GAME Lab"
description: "Genomics & Adaptive Mechanisms"
baseurl: ""
url: "https://gamelab-bio.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  - research.md
  - people.md
  - publications.md

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
